### ISSUE TITLE
BadMethodCallException Error occurs when adding an exhibit in Omeka Classic 

### ISSUE THREAD

**Issue by GitByrd** [DBinaghi/plugin-EmailNotification#3]
I have Omeka Classic 3.1.2 installed along with the Freedom theme 1.0.2. After installing the latest version of this plugin and upon testing, I noticed that this error occurred anytime I went to add a new exhibit in the admin, despite the role. Under the plugin's configuration settings, I unchecked the box that would notify if a new exhibit is added, but the error still persisted: 

**Full Error:** 

BadMethodCallException: Method named getElementTexts() does not exist. in /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Omeka/Record/AbstractRecord.php:262
Stack trace:
#0 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Omeka/Record/AbstractRecord.php(212): Omeka_Record_AbstractRecord->delegateToMixins('getElementTexts', Array)
#1 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/views/helpers/Metadata.php(183): Omeka_Record_AbstractRecord->__call('getElementTexts', Array)
#2 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/views/helpers/Metadata.php(149): Omeka_View_Helper_Metadata->_getElementText(Object(Exhibit), 'Dublin Core', 'Title')
#3 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/views/helpers/Metadata.php(73): Omeka_View_Helper_Metadata->_getText(Object(Exhibit), Array)
#4 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Zend/View/Abstract.php(350): Omeka_View_Helper_Metadata->metadata(Object(Exhibit), Array, Array)
#5 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/globals.php(2062): Zend_View_Abstract->__call('metadata', Array)
#6 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/plugins/EmailNotification/EmailNotificationPlugin.php(266): metadata(Object(Exhibit), Array)
#7 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/plugins/EmailNotification/EmailNotificationPlugin.php(248): EmailNotificationPlugin->notifyUsers('exhibit', Object(Exhibit))
#8 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Omeka/Plugin/Broker.php(154): EmailNotificationPlugin->hookAfterSaveExhibit(Array)
#9 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Omeka/Record/AbstractRecord.php(302): Omeka_Plugin_Broker->callHook('after_save_exhi...', Array)
#10 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Omeka/Record/AbstractRecord.php(549): Omeka_Record_AbstractRecord->runCallbacks('afterSave', Array)
#11 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Omeka/Controller/AbstractActionController.php(204): Omeka_Record_AbstractRecord->save(false)
#12 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Zend/Controller/Action.php(516): Omeka_Controller_AbstractActionController->addAction()
#13 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#14 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#15 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch()
#16 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#17 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#18 /home/schaffer/academic.schafferlibrarycollections.org/samurai-armor/admin/index.php(28): Omeka_Application->run()
#19 {main}

**Comment by DBinaghi** [comment]
Hi. Please upgrade the EmailNotification plugin to its 1.5 version and let me know if that fixes the problem
